//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchGhoraan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public int Id { get; set; }
        public int ChapterId { get; set; }
        public string Keyword1 { get; set; }
        public string NormalizedKeyword { get; set; }
        public string NormalizedFarisKeyword { get; set; }
    
        public virtual Chapter Chapter { get; set; }
    }
}
